<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Observables.NuGetSmoke.RestAPI.Reactive</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Observables.RestAPI.Reactive" Version="$(ObservablesConsumerPackageVersion)" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <PackageReference Include="RichardSzalay.MockHttp" Version="7.0.0" />
  </ItemGroup>
</Project>
