<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.R3.props" />
  <Import Project="..\..\Observables.SourceGenerators.InterfaceProxy.props" />

  <PropertyGroup>
    <Description>Source generator for gRPC proxies → R3 Observable.</Description>
    <DefineConstants>$(DefineConstants);ROSLYN_4;GRPC_R3</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="R3" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="..\Observables.Grpc.SourceGenerators.Shared\Observables.Grpc.SourceGenerators.Shared.projitems" Label="Shared" />

</Project>
