<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.Mqtt.Reactive</RootNamespace>
    <AssemblyName>Observables.Mqtt.Reactive</AssemblyName>
    <Description>System.Reactive bridges for Observables.Mqtt.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.Mqtt\Observables.Mqtt.csproj" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

</Project>
