<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <RootNamespace>Observables.Mqtt.Reactive</RootNamespace>
    <AssemblyName>Observables.Mqtt.Reactive</AssemblyName>
    <Description>System.Reactive bridges for Observables.Mqtt.</Description>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.Mqtt\Observables.Mqtt.csproj" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

</Project>
