<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.R3.props" />

  <PropertyGroup>
    <Description>Source generator for MQTT topic proxies → R3 Observable.</Description>
    <DefineConstants>$(DefineConstants);ROSLYN_4;MQTT_R3</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Observables.Shared\Observables.SourceGenerators.Shared\Observables.SourceGenerators.Shared.csproj" />
    <PackageReference Include="R3" Version="1.3.0" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="..\Observables.Mqtt.SourceGenerators.Shared\Observables.Mqtt.SourceGenerators.Shared.projitems" Label="Shared" />

</Project>
