<Project>

  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Skymly</Authors>
    <Copyright>Copyright (c) Skymly. All rights reserved.</Copyright>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <Import Project="eng\Observables.ProjectDefaults.props" />

</Project>
