<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.props" />

  <PropertyGroup>
    <Description>Source generator for declarative REST clients → System.Reactive IObservable.</Description>
    <DefineConstants>$(DefineConstants);ROSLYN_4;RESTAPI_SYSTEM_REACTIVE</DefineConstants>
  </PropertyGroup>


  <Import Project="..\Observables.RestAPI.SourceGenerators.Shared\Observables.RestAPI.SourceGenerators.Shared.projitems" Label="Shared" />

</Project>
