<Project Sdk="Microsoft.Build.Traversal/4.1.82">

  <PropertyGroup>
    <Description>Traversal root for Observables.Nats.R3 and Observables.Nats.Reactive NuGet packages.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Observables.Nats.R3.csproj" />
    <ProjectReference Include="Observables.Nats.Reactive.Pack.csproj" />
  </ItemGroup>

</Project>
