<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.RestAPI</RootNamespace>
    <AssemblyName>Observables.RestAPI</AssemblyName>
    <Description>Declarative type-safe HTTP client runtime (Task and R3 Observable).</Description>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="R3" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Net.Http.Json" />
  </ItemGroup>

</Project>
