<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\eng\Observables.Package.props" />
  <Import Project="..\..\eng\PackRoslynAnalyzer.targets" />
  <Import Project="..\..\eng\PackReferencedProjects.targets" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>false</DevelopmentDependency>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <PackageId>Observables.Mqtt.R3</PackageId>
    <Description>Declarative MQTT topic proxies for R3 Observable.</Description>
    <PackageTags>observables;mqtt;r3;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ObservablesPackGeneratorProject>..\Observables.Mqtt.R3.SourceGenerators\Observables.Mqtt.R3.SourceGenerators.csproj</ObservablesPackGeneratorProject>
    <ObservablesPackGeneratorAssemblyName>Observables.Mqtt.R3.SourceGenerators.dll</ObservablesPackGeneratorAssemblyName>
    <ObservablesPackGeneratorOutputDir>$(MSBuildProjectDirectory)\..\Observables.Mqtt.R3.SourceGenerators\bin\$(Configuration)\netstandard2.0\</ObservablesPackGeneratorOutputDir>
    <ObservablesPackPackagePropsFile>$(MSBuildProjectDirectory)\build\Observables.Mqtt.R3.props</ObservablesPackPackagePropsFile>
  </PropertyGroup>

  <ItemGroup>
    <ObservablesPackLibProjectReference Include="..\Observables.Mqtt\Observables.Mqtt.csproj" />
    <PackageReference Include="R3" Version="1.3.0" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <None Include="README.Mqtt.R3.pack.md" Pack="true" PackagePath="README.md" Visible="false" />
  </ItemGroup>

</Project>
