<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.R3.props" />

  <PropertyGroup>
    <Description>Source generators for MQTT topics and payloads → R3 Observable.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Observables.Shared\Observables.SourceGenerators.Shared\Observables.SourceGenerators.Shared.csproj" />
  </ItemGroup>

</Project>
