<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.Mqtt.Reactive.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.Mqtt.Reactive\Observables.Mqtt.Reactive.csproj" />
    <ProjectReference Include="..\Observables.Mqtt.Reactive.SourceGenerators\Observables.Mqtt.Reactive.SourceGenerators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Observables.Mqtt.Tests\Infrastructure\MqttTestBroker.cs" Link="Infrastructure\MqttTestBroker.cs" />
    <Compile Include="..\Observables.Mqtt.Tests\Infrastructure\MqttTestBrokerFixture.cs" Link="Infrastructure\MqttTestBrokerFixture.cs" />
  </ItemGroup>

</Project>
