<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.Analyzers.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.Analyzers\Observables.Analyzers.csproj" />
    <ProjectReference Include="..\..\Observables.SignalR\Observables.SignalR\Observables.SignalR.csproj" />
    <ProjectReference Include="..\..\Observables.SignalR\Observables.SignalR.Reactive\Observables.SignalR.Reactive.csproj" />
    <ProjectReference Include="..\..\Observables.Mqtt\Observables.Mqtt\Observables.Mqtt.csproj" />
    <ProjectReference Include="..\..\Observables.Nats\Observables.Nats\Observables.Nats.csproj" />
    <ProjectReference Include="..\..\Observables.Postgres\Observables.Postgres\Observables.Postgres.csproj" />
    <ProjectReference Include="..\..\Observables.Redis\Observables.Redis\Observables.Redis.csproj" />
    <ProjectReference Include="..\..\Observables.Redis\Observables.Redis.Reactive\Observables.Redis.Reactive.csproj" />
    <ProjectReference Include="..\..\Observables.WebSocket\Observables.WebSocket\Observables.WebSocket.csproj" />
    <ProjectReference Include="..\..\Observables.RestAPI\Observables.RestAPI\Observables.RestAPI.csproj" />
    <ProjectReference Include="..\..\Observables.Grpc\Observables.Grpc\Observables.Grpc.csproj" />
    <ProjectReference Include="..\..\Observables.Sse\Observables.Sse\Observables.Sse.csproj" />
    <ProjectReference Include="..\..\Observables.Sse\Observables.Sse.Reactive\Observables.Sse.Reactive.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="R3" />
  </ItemGroup>

</Project>
