<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.WebSocket.Reactive.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.WebSocket\Observables.WebSocket.csproj" />
    <ProjectReference Include="..\Observables.WebSocket.Reactive\Observables.WebSocket.Reactive.csproj" />
    <ProjectReference Include="..\Observables.WebSocket.Reactive.SourceGenerators\Observables.WebSocket.Reactive.SourceGenerators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Observables.WebSocket.Tests\Infrastructure\WebSocketTestServer.cs"
             Link="Infrastructure\WebSocketTestServer.cs" />
    <Compile Include="..\Observables.WebSocket.Tests\Infrastructure\WebSocketTestServerFixture.cs"
             Link="Infrastructure\WebSocketTestServerFixture.cs" />
  </ItemGroup>

</Project>
