<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.props" />

  <PropertyGroup>
    <Description>Source generators for classic .NET events → System.Reactive (IObservable).</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" PrivateAssets="all" />
  </ItemGroup>

</Project>
