using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Observables.SourceGenerators.Shared;

/// <summary>
/// Standard prefix for analyzer-emitted source files (CS8669 / RS1035 friendly).
/// </summary>
internal static class GeneratedSourceHeader
{
    public static SyntaxTriviaList LeadingTrivia() =>
        TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
            Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)));

    public static CompilationUnitSyntax WithHeader(CompilationUnitSyntax unit)
    {
        if (HasHeader(unit))
        {
            return unit;
        }

        return unit.WithLeadingTrivia(LeadingTrivia().AddRange(unit.GetLeadingTrivia()));
    }

    public static string ToSource(CompilationUnitSyntax unit) =>
        WithHeader(unit).NormalizeWhitespace().ToFullString();

    private static bool HasHeader(CompilationUnitSyntax unit) =>
        unit.GetLeadingTrivia().Any(static t =>
            t.IsKind(SyntaxKind.SingleLineCommentTrivia)
            && t.ToString().Contains("auto-generated"));
}
