using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Observables.SourceGenerators.Shared;

/// <summary>
/// Standard prefix for analyzer-emitted source files (CS8669 / RS1035 friendly).
/// </summary>
internal static class GeneratedSourceHeader
{
    public static SyntaxTriviaList LeadingTrivia() =>
        TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
            Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)));

    public static CompilationUnitSyntax WithHeader(CompilationUnitSyntax unit)
    {
        if (HasHeader(unit))
        {
            return unit;
        }

        return unit.WithLeadingTrivia(LeadingTrivia().AddRange(unit.GetLeadingTrivia()));
    }

    public static string ToSource(CompilationUnitSyntax unit) =>
        WithHeader(unit).NormalizeWhitespace().ToFullString();

    public static void WritePrefix(SourceWriter writer, Nullability nullability = Nullability.None)
    {
        writer.WriteLine("// <auto-generated/>");
        if (nullability == Nullability.Enabled)
        {
            writer.WriteLine("#nullable enable");
        }
        else if (nullability == Nullability.Disabled)
        {
            writer.WriteLine("#nullable disable");
        }

        writer.WriteLine("#pragma warning disable");
    }

    public static SourceText ToSourceText(string body, Nullability nullability = Nullability.None)
    {
        var sb = new StringBuilder();
        AppendPrefix(sb, nullability);
        sb.AppendLine(body.Trim());
        sb.AppendLine("#pragma warning restore");
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static void AppendPrefix(StringBuilder sb, Nullability nullability)
    {
        sb.AppendLine("// <auto-generated/>");
        if (nullability == Nullability.Enabled)
        {
            sb.AppendLine("#nullable enable");
        }
        else if (nullability == Nullability.Disabled)
        {
            sb.AppendLine("#nullable disable");
        }

        sb.AppendLine("#pragma warning disable");
    }

    private static bool HasHeader(CompilationUnitSyntax unit) =>
        unit.GetLeadingTrivia().Any(static t =>
            t.IsKind(SyntaxKind.SingleLineCommentTrivia)
            && t.ToString().Contains("auto-generated"));
}
