<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.props" />
  <Import Project="..\..\Observables.SourceGenerators.InterfaceProxy.props" />

  <PropertyGroup>
    <Description>Source generator for WebSocket proxies → System.Reactive IObservable.</Description>
    <DefineConstants>$(DefineConstants);ROSLYN_4;WEBSOCKET_REACTIVE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="..\Observables.WebSocket.SourceGenerators.Shared\Observables.WebSocket.SourceGenerators.Shared.projitems" Label="Shared" />

</Project>
