<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\eng\Observables.Package.props" />
  <Import Project="..\..\eng\PackRoslynAnalyzer.targets" />
  <Import Project="..\..\eng\PackReferencedProjects.targets" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>false</DevelopmentDependency>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <PackageId>Observables.WebSocket.Reactive</PackageId>
    <Description>Declarative WebSocket proxies for System.Reactive IObservable.</Description>
    <PackageTags>observables;websocket;system.reactive;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ObservablesPackGeneratorProject>..\Observables.WebSocket.Reactive.SourceGenerators\Observables.WebSocket.Reactive.SourceGenerators.csproj</ObservablesPackGeneratorProject>
    <ObservablesPackGeneratorAssemblyName>Observables.WebSocket.Reactive.SourceGenerators.dll</ObservablesPackGeneratorAssemblyName>
    <ObservablesPackGeneratorOutputDir>$(MSBuildProjectDirectory)\..\Observables.WebSocket.Reactive.SourceGenerators\bin\$(Configuration)\netstandard2.0\</ObservablesPackGeneratorOutputDir>
    <ObservablesPackPackagePropsFile>$(MSBuildProjectDirectory)\build\Observables.WebSocket.Reactive.props</ObservablesPackPackagePropsFile>
  </PropertyGroup>

  <ItemGroup>
    <ObservablesPackLibProjectReference Include="..\Observables.WebSocket\Observables.WebSocket.csproj" />
    <ObservablesPackLibProjectReference Include="..\Observables.WebSocket.Reactive\Observables.WebSocket.Reactive.csproj" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <None Include="README.WebSocket.Reactive.pack.md" Pack="true" PackagePath="README.md" Visible="false" />
  </ItemGroup>

</Project>
