<Project Sdk="Microsoft.Build.Traversal/4.1.82">

  <PropertyGroup>
    <Description>Traversal root for Observables.SignalR.R3 and Observables.SignalR.Reactive NuGet packages.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Observables.SignalR.R3.csproj" />
    <ProjectReference Include="Observables.SignalR.Reactive.Pack.csproj" />
  </ItemGroup>

</Project>
