<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\eng\Observables.Package.props" />
  <Import Project="..\..\eng\PackRoslynAnalyzer.targets" />
  <Import Project="..\..\eng\PackReferencedProjects.targets" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>false</DevelopmentDependency>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <PackageId>Observables.SignalR.Reactive</PackageId>
    <Description>Declarative SignalR hub client proxies for System.Reactive IObservable.</Description>
    <PackageTags>observables;signalr;system.reactive;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ObservablesPackGeneratorProject>..\Observables.SignalR.Reactive.SourceGenerators\Observables.SignalR.Reactive.SourceGenerators.csproj</ObservablesPackGeneratorProject>
    <ObservablesPackGeneratorAssemblyName>Observables.SignalR.Reactive.SourceGenerators.dll</ObservablesPackGeneratorAssemblyName>
    <ObservablesPackGeneratorOutputDir>$(MSBuildProjectDirectory)\..\Observables.SignalR.Reactive.SourceGenerators\bin\$(Configuration)\netstandard2.0\</ObservablesPackGeneratorOutputDir>
    <ObservablesPackPackagePropsFile>$(MSBuildProjectDirectory)\build\Observables.SignalR.Reactive.props</ObservablesPackPackagePropsFile>
  </PropertyGroup>

  <ItemGroup>
    <ObservablesPackLibProjectReference Include="..\Observables.SignalR\Observables.SignalR.csproj" />
    <ObservablesPackLibProjectReference Include="..\Observables.SignalR.Reactive\Observables.SignalR.Reactive.csproj" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
    <None Include="README.SignalR.Reactive.pack.md" Pack="true" PackagePath="README.md" Visible="false" />
  </ItemGroup>

</Project>
