<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Observables.SourceGenerators.props" />

  <PropertyGroup>
    <Description>Source generators for MQTT topics and payloads → reactive streams.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.SourceGenerators.Shared\Observables.SourceGenerators.Shared.csproj" />
  </ItemGroup>

</Project>
