<Project Sdk="Microsoft.Build.Traversal/4.1.82">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Description>Traversal root for Observables.RestAPI.R3 and Observables.RestAPI.Reactive NuGet packages.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Observables.RestAPI.R3.csproj" />
    <ProjectReference Include="Observables.RestAPI.Reactive.Pack.csproj" />
  </ItemGroup>

</Project>
