<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.RestAPI.HttpClientFactory</RootNamespace>
    <AssemblyName>Observables.RestAPI.HttpClientFactory</AssemblyName>
    <Description>Microsoft.Extensions.DependencyInjection extensions for Observables.RestAPI clients.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.RestAPI\Observables.RestAPI.csproj" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
