<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\eng\Observables.Package.props" />
  <Import Project="..\..\eng\PackRoslynAnalyzer.targets" />
  <Import Project="..\..\eng\PackReferencedProjects.targets" />

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>false</DevelopmentDependency>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <PackageId>Observables.Grpc.R3</PackageId>
    <Description>Declarative gRPC proxies for R3 Observable.</Description>
    <PackageTags>observables;grpc;r3;source-generator</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ObservablesPackGeneratorProject>..\Observables.Grpc.R3.SourceGenerators\Observables.Grpc.R3.SourceGenerators.csproj</ObservablesPackGeneratorProject>
    <ObservablesPackGeneratorAssemblyName>Observables.Grpc.R3.SourceGenerators.dll</ObservablesPackGeneratorAssemblyName>
    <ObservablesPackGeneratorOutputDir>$(MSBuildProjectDirectory)\..\Observables.Grpc.R3.SourceGenerators\bin\$(Configuration)\netstandard2.0\</ObservablesPackGeneratorOutputDir>
    <ObservablesPackPackagePropsFile>$(MSBuildProjectDirectory)\build\Observables.Grpc.R3.props</ObservablesPackPackagePropsFile>
  </PropertyGroup>

  <ItemGroup>
    <ObservablesPackLibProjectReference Include="..\Observables.Grpc\Observables.Grpc.csproj" />
    <PackageReference Include="R3" />
    <None Include="README.Grpc.R3.pack.md" Pack="true" PackagePath="README.md" Visible="false" />
  </ItemGroup>

</Project>
