<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Observables.Nats.Reactive.SourceGenerators.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Observables.Nats\Observables.Nats.csproj" />
    <ProjectReference Include="..\Observables.Nats.Reactive\Observables.Nats.Reactive.csproj" />
    <ProjectReference Include="..\Observables.Nats.Reactive.SourceGenerators\Observables.Nats.Reactive.SourceGenerators.csproj" />
  </ItemGroup>

</Project>
