<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Observables.SourceGenerators.R3.props" />

  <PropertyGroup>
    <Description>Source generator for declarative REST clients → R3 Observable.</Description>
    <DefineConstants>$(DefineConstants);ROSLYN_4;RESTAPI_R3</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Observables.Shared\Observables.SourceGenerators.Shared\Observables.SourceGenerators.Shared.csproj" />
    <PackageReference Include="R3" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="..\Observables.RestAPI.SourceGenerators.Shared\Observables.RestAPI.SourceGenerators.Shared.projitems" Label="Shared" />

</Project>
